name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Use Node 16.x (Angular 14 compatible) and cache npm deps
      - name: Use Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
          cache: 'npm'

      # 3. Install dependencies from lockfile (legacy peer deps for old packages)
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4. Build Angular app
      - name: Build Angular
        run: npm run build

      # 5. Install Playwright browsers & deps
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --force

      # 6. Run Playwright UI tests
      - name: Run Playwright Tests
        run: npm run uiComponents-chrome

      # 7. Upload Playwright HTML report as GitHub artifact
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30